[32mINFO    [0m py_test_api.tests.conftest:conftest.py:29 Verifying endpoint connection...
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1053 Starting new HTTPS connection (1): todo.pixegami.io:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:547 https://todo.pixegami.io:443 "GET / HTTP/1.1" 200 39
[35mDEBUG   [0m py_test_api.utils.api_method_helper:api_method_helper.py:105 Creating a new payload [user_id: test_user_fd36a0b8bd544e9daa6d43634d6d8d9c, content: test_content_180f054e950c4f499532907d96ce8546]
[35mDEBUG   [0m py_test_api.utils.api_method_helper:api_method_helper.py:61 Starting PUT request [payload: {'content': 'test_content_180f054e950c4f499532907d96ce8546', 'user_id': 'test_user_fd36a0b8bd544e9daa6d43634d6d8d9c', 'is_done': False}]
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1053 Starting new HTTPS connection (1): todo.pixegami.io:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:547 https://todo.pixegami.io:443 "PUT /create-task HTTP/1.1" 200 232